version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: urlshort_db
    environment:
      POSTGRES_USER: urlshort
      POSTGRES_PASSWORD: urlshort
      POSTGRES_DB: urlshort
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshort -d urlshort"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  dbdata:
